spring:
  datasource:
    # Kết nối qua cổng 3306 của MySQL Local, tự tạo DB nếu chưa có
    url: jdbc:mysql://localhost:3306/smartmatch_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    password: 1234 # <-- LƯU Ý: Đảm bảo khớp với mật khẩu MySQL trên máy bạn
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    com.smartmatch: DEBUG
    org.hibernate.SQL: DEBUG